// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  LineComment = 1,
  Program = 2,
  Array = 3,
  String = 4,
  Char = 5,
  Integer = 6,
  Floating = 7,
  Fraction = 8,
  SpecialNumber = 9,
  Glyph = 10,
  Inline = 11,
  Signature = 12,
  Binding = 13,
  Identifier = 14
